version: '3.7'

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "fidibo"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  api:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/app/
  bookcache:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  mysql_data:

